name: Build KernelSU for Xiaomi MI 8 (dipper)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout KernelSU Action
      uses: actions/checkout@main

    - name: KernelSU build
      uses: xiaoleGun/KernelSU_Action@main
      with:
        kernel_url: "https://github.com/LineageOS/android_kernel_xiaomi_sdm845.git"
        kernel_branch: "lineage-18.1"
        defconfig: "sdm845_defconfig"
        anykernel3: "true"
        enable_kernelsu: "true"
        kernelsu_version: "v1.0.2"
        clang_version: "r365631c"
